application: mamchecker
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

    #this if using openid ?
    #- url: /_ah/login_required
    #  script: do_openid_login.py

    - url: /favicon\.ico
      static_files: mamchecker/static/favicon.ico
      upload: mamchecker/static/favicon\.ico
      mime_type: image/x-icon

    - url: /static
      static_dir: mamchecker/static

    - url: /[^/]*/_images
      static_dir: mamchecker/_images

    - url: .*
      script: mamchecker.app.app
      secure: optional

    #This, if below builtins remote_api is off
    #- url: /admin/.*
    #  script: google.appengine.ext.admin.application
    #  login: admin
    #
    

#error_handlers:
#  - file: mamchecker/error_default.html
#  - error_code: over_quota
#    file: error_over_quota.html
#  - error_code: dos_api_denial
#    file: error_dos_api_denial.html
#  - error_code: timeout
#    file: error_timeout.html


#/_ah/remote_api
builtins:

    - remote_api: on

libraries:

    - name: webapp2
      version: latest
    - name: numpy
      version: latest
    #- name: jinja2
    #  version: latest
    - name: matplotlib
      version: latest
    - name: lxml
      version: latest

skip_files:

    - ^(.*/)?#.*#

    - ^(.*/)?.*~
    - ^(.*/)?.*\.py[co]
    - ^(.*/)?.*/RCS/.*
    - ^(.*/)?\..*
    - ^(.*/)?\.rst

